# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static-pv
  namespace: test-csi
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  csi:
    nodePublishSecretRef:
      name: "mapr-ticket-secret"
      namespace: "test-csi"
    driver: com.mapr.csi-nfskdf
    volumeHandle: test-id
    volumeAttributes:
      volumePath: CHANGETHIS # Default: "/"
      cluster: CHANGETHIS
      cldbHosts: CHANGETHIS
      securityType: "secure" # Default: Unsecure